conf/RunConfig.yaml.L3_HLS.jinja2.tmpl, docker/hysds-io.json.SCIFLO_L3_DSWx_HLS, docker/hysds-io.json.SCIFLO_L3_DSWx_HLS_on_demand, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, docker/job-spec.json.SCIFLO_L3_DSWx_HLS_on_demand, on_demand/run_on_demand.py, on_demand/run_on_demand.sh, opera_chimera/configs/pge_configs/PGE_L3_HLS.yaml
This PR adds a new job spec which allows submission of an on-demand DSWx-HLS PGE job from the Tosca UI:
The job allows the operator to tweak the available DSWx-HLS parameters, and to specify the HLS dataset ID to run the PGE with. If the HLS dataset has not been ingested (no entry found in the state config elasticsearch index), the job will fail.
=> On-demand DSWx-HLS Jobs

cluster_provisioning/dev-common/variables.tf, cluster_provisioning/dev-e2e-baseline-pge/variables.tf, cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_HLS.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_HLS.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/settings.yaml, opera_chimera/configs/pge_configs/PGE_L3_HLS.yaml, tests/util/test_pge_util.py, util/pge_util.py
This PR updates PCM to utilize the 1.0.0-rc.2.0 version of the DSWx-HLS PGE.
Notable updates with the new PGE version:
- Utilizes the CalVal release of the DSWx-HLS SAS
- Fixes several issues with the ISO 19115 metadata file sent to PO.DAAC
- Product Counter usage has been removed from all output file names (PCM updated to match)
=> DSWx-HLS PGE 1.0.0-rc.2.0 update

cluster_provisioning/dev-common/variables.tf, cluster_provisioning/dev-e2e-baseline-pge/variables.tf, cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/override.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/pge_outputs.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/settings.yaml, opera_chimera/configs/pge_configs/PGE_L3_HLS.yaml, tests/util/test_pge_util.py, util/pge_util.py
This branch makes the updates to support the 1.0.0-RC.3.0 build of the DSWx-HLS PGE. The main change in that release is a modification to the output filename conventions, where some fields have been shuffled around.
@hhlee445 Please ensure this branch gets merged (once you've tested) before this one: https://github.com/nasa/opera-sds-pcm/pull/192. Once it is merged, I will update the CSLC-S1 integration branch to comply with the changes from this branch.
=> DSWx-HLS v1.0.0-RC.3.0 Integration

integration/test_integration.py
typo causing smoke tests to fail due to missing function with given name. function was renamed previously.
Refs #205
=> feat(tests): fix typo

opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1.yaml, opera_chimera/configs/pge_configs/PGE_L3_DSWx_HLS.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/opera_chimera/test_precondition_functions.py, util/pge_util.py, wrapper/pge_functions.py
This branch updates the opera_chimera precondition functions to dynamically stage a DEM file based on the swath covered by the input S1 SLC SAFE archive.
In order to obtain the bounding box from the SAFE metadata, a precondition function has been added to manually localize the SAFE zip file to a worker. From there, a second precondition function extracts the lat/lon bounding box from the relevant metadata, and uses it with the stage_dem tool to obtain the appropriate region from the opera-dem S3 bucket.
Note: there are also some kludge fixes to address a validation issue in the current engineering release of the CSLC-S1 PGE. These should be addressed with the next PGE ER.
=> R2 PGE DEM Staging

cluster_provisioning/modules/common/main.tf
Fixing typo in DSWX log file name which was preventing cloudwatch from collecting the logs.
Refs #159
=> issue 159: feat(logging): fix typo in log name for DSWX PGE

tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
Initial addition of the script which will eventually be used to download an Orbit file which corresponds to the input SLC SAFE archive used with a CSLC/RTC-S1 job. A unit test suite has also been included for the script under `test/tools`
The script has a simple command-line interface, and its in default configuration should only require the name of the SLC SAFE archive to obtain the Orbit file for:
```
stage_orbit_file.py /path/to/S1B_IW_SLC__1SDV_20180504T104507_20180504T104535_010770_013AEE_919F.zip
```
The input SAFE file name need not include a directory path or extension:
```
stage_orbit_file.py S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC
```
By default, the correct endpoints for the Orbit file query/download REST services are utilized with public credentials …
=> Orbit File Staging Script

data_subscriber/daac_data_subscriber.py
Token code was interpreting a list element as a string when it should have been interpreting as a dict. Closes #274
=> Fix explicit typing for token functions

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-releaser/variables.tf
increase root device disk space across multiple environments, basing this new minimum off of the `dev` environment which does not exhibit smoke test failures.
smoke test failures were caused by Elasticsearch on mozart entering read-only mode due to exhausted disk space.
Refs #283
=> issue 283: feat(mozart): increase root device disk space to fix smoke tests

cluster_provisioning/modules/common/variables.tf, data_subscriber/daac_data_subscriber.py, data_subscriber/slc/slc_catalog.py, tests/data_subscriber/test_daac_data_subscriber.py, tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
This PR updates the stage_orbit_file.py tool to support querying/downloading of Restitued Orbit File (ROEORB) in addition to the current support for Precise Orbit (POEORB) files. Selection of the orbit file type is accomplished via a --orbit-type argument added to stage_orbit_file.py.
The daac_data_subscriber.py script has also been updated to fall back to querying for RESORB files if an initial query for POEORB files returns no results.
In the course of testing this branch, I discovered that ASF DAAC had started serving s3 URL's in addition to the HTTPS locations, so the subscriber script has been updated to store the s3 URL's, if provided, in elasticsearch along side the HTTPS address. When downloading, if HTTPS is present it is still prioritized over the S3 location.
Lastly, the branch …
=> Restitued Orbit File Support 

data_subscriber/daac_data_subscriber.py, opera_chimera/precondition_functions.py, util/geo_util.py
This branch addresses the issues with longitudinal striping in DSWx-HLS products by adjusting the amount of margin used when acquiring the tile-based ancillary inputs (DEM and worldcover).
As an added bonus, this branch also adds support for including wildcards supported by CMR (* and ?) in the native-id argument of the daac_data_subscriber.py script.
=> DSWx-HLS Ancillary Margin Fix

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/variables.tf, cluster_provisioning/pst/variables.tf, conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L2_CSLC_S1.yaml, conf/schema/RunConfig_schema.L2_RTC_S1.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1, opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1.yaml, opera_chimera/configs/pge_configs/PGE_L2_RTC_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, product2dataset/product2dataset.py, tests/opera_chimera/test_precondition_functions.py, util/pge_util.py
This branch updates OPERA PCM to utilize v2.0.0-er.4.0 of the R2 PGEs (CSLC-S1, RTC-S1).
The high level changes are as follows:
- Updated file naming conventions for CSLC/RTC output products to use hyphens for product shortname, as well as capitalize burst ID portion of file name
- Precondition logic for both CSLC and RTC now obtains the s3 path to the orbit file obtained by the downloader script
- Added a precondition function to assign the appropriate polarization value based on the name of the input SLC granule (RTC-S1 only, CSLC will get added with beta delivery)
- Bumped the soft/hard time limit for RTC-S1 to 90 minutes, since it takes about an hour for the PGE to process all available bursts
Note that due to limitations with the current version of the CSLC-S1 SAS, the 2.0.0-er.4.0 …
=> R2 PGE ER4.0 Integration

conf/settings.yaml, tests/util/test_pge_util.py
- Update expected_output_base_name for CSLC & RTC simulated tests
- Add 'product_version' as Dataset_Version_Key for L2_CSLC_S1 & L2_RTC_S1
=> issue_331: Additional fix for PGE r2_er4.0_integration

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/variables.tf, cluster_provisioning/pst/variables.tf, conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DSWx_HLS.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, docker/job-spec.json.SCIFLO_L3_DSWx_HLS_on_demand, opera_chimera/configs/pge_configs/PGE_L3_DSWx_HLS.yaml, product2dataset/product2dataset.py, tests/util/test_pge_util.py, util/pge_util.py
This branch integrates the RC6.0 delivery of the DSWx-HLS PGE with OPERA PCM.
Changes with this version include incorporation of the v3.2 CalVal SAS delivery, support for using a hyphen in the product shortname (DSWx-HLS), and support for including both the PNG and GeoTIFF Browse images with each output HySDS dataset.
=> DSWx-HLS PGE RC6.0 Integration

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/int_override.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/override.tf, cluster_provisioning/ops/variables.tf, cluster_provisioning/pst/override.tf, cluster_provisioning/pst/variables.tf, conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl, conf/schema/RunConfig_schema.L3_DSWx_HLS.yaml, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, docker/job-spec.json.SCIFLO_L3_DSWx_HLS_on_demand, opera_chimera/configs/pge_configs/PGE_L3_DSWx_HLS.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, wrapper/pge_functions.py
This branch integrates the RC7.0 delivery of the DSWx-HLS PGE with OPERA PCM.
Changes with this version include incorporation of the CalVal v3.3 delivery of the DSWx-HLS SAS and adds support for usage of the Shoreline shapefile static ancillary input products.
=> DSWx-HLS PGE RC7.0 Integration

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/int_override.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/variables.tf, cluster_provisioning/pst/variables.tf, conf/pge_outputs.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/settings.yaml, docker/job-spec.json.SCIFLO_L2_RTC_S1, opera_chimera/opera_pge_job_submitter.py, opera_chimera/precondition_functions.py
This branch addresses several issues encountered during testing of both the R1 and R2 PGE's with OPERA PCM. This includes:
* Fix to the regular expressions for R2 output product file names to include missing Polarization modes (resolves #378)
* Integration of v2.0.0-er.5.1 of the RTC-S1 PGE, which addresses SAS failures from a validation check which was no longer needed
* Update to the margin value used for DSWx-HLS ancillary inputs staged by PCM to address non-overlap errors raised by the SAS
* Adds "pge_output_dir" to the `_triage_additional_globs` setting for all PGE jobs to ensure we capture the PGE/SAS log file for any failed job
This branch was tested with the following HLS inputs which had failed due to DEM non-overlap:
- HLS.S30.T33QWU.2022126T093041.v2.0
- …
=> R2 Product Filename Fix/DEM Overlap workaround

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/int_override.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/override.tf, cluster_provisioning/ops/variables.tf, cluster_provisioning/pst/override.tf, cluster_provisioning/pst/variables.tf, conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, docker/job-spec.json.SCIFLO_L3_DSWx_HLS_on_demand, opera_chimera/precondition_functions.py, tools/stage_dem.py
This branch integrates the RC7.1 delivery of the DSWx-HLS PGE with OPERA PCM.
Changes with this version include incorporation of the CalVal v3.4 delivery of the DSWx-HLS SAS, which addresses issues with the ancillary input overlap validation check.
=> DSWx-HLS RC 7.1 Integration

conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl
This PR sets the `check_ancillary_inputs_coverage` flag to False in the template RunConfig for DSWx-HLS. This check is disabled while a bug is corrected in the SAS to fix the anti-meridian case with the global Landcover file.
The underlying SAS issue is being addressed here: https://github.com/nasa/PROTEUS/pull/43
=> Disable Ancillary Overlap Check for DSWx-HLS

tools/stage_dem.py, tools/stage_worldcover.py, util/geo_util.py
This PR fixes `stage_dem.py` and `stage_worldcover.py` to properly handle the antimeridian ("dateline") crossing.
If the antimeridian crossing is detected for `stage_dem.py` and `stage_worldcover.py`, the function `check_dateline()` in `geo_util.py` divides the cropping polygon into two parts, one at the left side, and another one at the right side of the antimeridian crossing. In the current implementation, the polygon at the right side of the antimeridian crossing has longitude values greater than or equal `+180`. However, the input datasets, i.e. the DEM prepared for OPERA (based on the Copernicus DEM) and the ESA Worldcover have longitude ranges around [`-180`, `+180`]. The current version of GDAL translate does not wraps the cropping coordinates above `180` down to `-180` in order to …
=> Update `stage_dem.py` and `stage_worldcover.py` to properly handle the antimeridian crossing

product2dataset/product2dataset.py, tests/product2dataset/test_product2dataset.py
This branch fixes a bug where the S3 paths for DSWx-HLS output product locations was not in sync with the recent change to store products under the PGE shortname (ex DSWx_HLS).
=> DSWx-HLS Elasticsearch S3 Path Fix

integration/conftest.py, integration/int_test_util.py, integration/test_integration.py
Tests were failing due to DSWX version number reference change in generated IDs. Also, generated IDs are now dynamic, breaking asserts.
Refs #429
=> issue 429: fix(integration-tests): fix HLS tests.

conf/settings.yaml, opera_chimera/precondition_functions.py, tests/opera_chimera/test_precondition_functions.py
This branch exposes the margin value used when staging the DEM and worldcover ancillaries files for DSWx-HLS jobs in settings.yaml. This should hopefully make it easier to adjust the value as necessary without necessitating a full redeployment.
Note this branch does not resolve the current issue with the overlap check on anti-meridian HLS tiles.
=> DSWx-HLS ancillary margin setting

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/override.tf, cluster_provisioning/pst/override.tf, conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, docker/job-spec.json.SCIFLO_L3_DSWx_HLS_on_demand
This branch integrates the latest v1.0.1 release of the DSWx-HLS PGE, which wraps the corresponding version of the SAS. This version fixes more issues in the SAS when performing the DEM overlap check on HLS tiles that cross the anti-meridian/dateline.
Note: while updating the terraform scripts, I noticed that an unresolved code conflict was checked in for the `cluster_provisioning/ops/override.tf` file. I have resolved the conflicting section as part of the PR.
=> DSWx-HLS PGE v1.0.1 Integration

tools/stage_dem.py, tools/stage_worldcover.py, util/geo_util.py
This PR fixes `stage_dem.py` and `stage_worldcover.py` for the case in which the MGRS tile does not cross the antimeridian, but the added margin should result in antimeridian crossing. The fact that the MGRS tile does not cross the dateline prevents the current code from detecting the antimeridian crossing and subsequently dividing the tile polygon into two pieces.
The solution is to add the margin before the antimeridian crossing test. This PR adds the margin (in km) to the tile coordinates in meters, which may be preferable, but keeps them conversion using the meters-to-degrees conversion at the Equator (i.e., with longitude margin matching the latitude margin) as the default. This option is selected by the flag `flag_use_m_to_deg_conversion_at_equator` in the call to the function …
=> Add margin before antimeridian crossing test

util/geo_util.py
This PR fixes an "index out of range" error in the `check_dateline()` function. In some specific cases, it's possible that the input polygon does not cross the antimeridian, but it still enters the dateline check condition. For example, if the longitude range of a tile is [179, -180.5], the tile is completely contained in the left side of the antimeridian and does not cross the antimeridian line. This PR updates `check_dateline()` to handle the case in which the list of polygons obtained from the antimeridian split will have 1 element (i.e., one polygon), and not 2 as expected from the current code. 
Edit: This PR also updates the computation of min and max longitude values in `polygon_from_mgrs_tile()`. Longitude values "wrap" around the antimeridian crossing. For example, 179 degrees + …
=> Fix "index out of range" in check_dateline() function 

data_subscriber/download.py, opera_chimera/precondition_functions.py, tests/data_subscriber/test_daac_data_subscriber.py, tools/stage_ionosphere_file.py
This branch makes the following corrections to the workflow for downloading an Ionosphere correction file for use with CSLC-S1 jobs:
- The Ionosphere staging script now supports downloading both the "jplg" (latency 48 hours) and the "jprg" (latency 24-36 hours) types.
- The DAAC download script will now attempt to download a "jplg" file type, and if is not found then it will try to download the "jprg" type.
- If neither Ionosphere type can be found by the DAAC download script, then only a warning will be logged, rather than failing the entire SLC download job. This means only the CLSC-S1 jobs will now fail if no Ionosphere file was downloaded. RTC-S1 jobs will be unaffected.
- The DAAC download script only downloads Ionosphere files for SLC archives that intersect North America (meaning …
=> Ionosphere workflow corrections

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/settings.yaml, docker/job-spec.json.SCIFLO_L2_CSLC_S1
This branch integrates v2.0.0-rc.1.2 of the CSLC-S1 PGE into PCM. This version resolves the long runtime issue for generation of CSLC-S1 static layers. Static layer generation for CSLC-S1 has been re-enabled in settings.yaml.
This branch was tested with a single SLC archive on both c6[a/i].2xlarge and c6[a/i].4xlarge instances. The runtimes were:
**c6a.2xlarge/c6i.2xlarge**
SAS runtime: 2:44:03 (hr:min:sec)
PGE/SAS runtime: 10348.026279071
PCM runtime (PGE/SAS runtime + upload time to S3 rolling storage): 11355.594818s
**c6a.4xlarge/c6i.4xlarge**
SAS runtime: 1:38:33 (hr:min:sec)
PGE/SAS runtime: 6230.522144275 sec
PCM runtime (PGE/SAS runtime + upload time to S3 rolling storage): 7147.259063 sec
The instance types for the CSLC-S1 workers have been updated to the c6[a/i].4xlarge instances …
=> CSLC-S1 v2.0.0 RC.1.2 integration

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl, conf/schema/RunConfig_schema.L2_CSLC_S1.yaml, conf/settings.yaml, data_subscriber/download.py, docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist, docker/job-spec.json.SCIFLO_L2_RTC_S1, tools/stage_orbit_file.py
This branch integrates the v2.0.0-rc.1.3 releases of the R2 PGEs into PCM. It also updates the stage_orbit_file.py script to expose the date range used when querying as a command-line argument. This value can be set in settings.yaml so it may be adjusted without requiring a redeployment. The default for POEORB files in settings.yaml has been set to 2 days to resolve orbit file download errors for a particular time range in April 2021.
The following issues were tested with this release to ensure the processing now completes successfully:
* RTC-S1 processing fails with `KeyError: 't175_371592_iw1'` - Tested with data set S1A_IW_SLC__1SDV_20210419T162132_20210419T162200_037521_046C9E_CF36
* SLC Download fails to find an Orbit file for time range in April 2021 - Tested with data set …
=> R2 PGE 2.0.0 RC 1.3 Integration

data_subscriber/download.py
When downloading batch id length is 1, do a direct ES query for that granule id to save resources.
=> Issue 500 r2: Handle native-id download for HLS and SLC 

cluster_provisioning/modules/common/variables.tf
Note: AWS price sheet updates occurred recently to make larger C5 spot machines less desirable for some OPERA workloads.
Refs #545
=> Issue 545: perf(slc): optimize EC2 instance types.

tests/geo/test_geo_util.py, tools/stage_dem.py, util/geo_util.py
This branch fixes an issue in stage_dem.py where a provided bounding box was not padded with margin properly for regions at high latitudes. A new function named polygon_from_bounding_box() has been added to geo_util.py to handle application of margin to the bounding box used to obtain the corresponding DEM.
This branch was tested on a dev cluster using the following input SLC's which exhibit the high latitude behavior:
-   S1A_IW_SLC__1SDH_20230628T122459_20230628T122529_049186_05EA1E_AD77
-   S1A_IW_SLC__1SDH_20230628T122527_20230628T122546_049186_05EA1E_4B0C
-   S1A_IW_SLC__1SDH_20230628T122652_20230628T122722_049186_05EA20_0BC9
For all cases, the DEM staged with 100km of margin were now sufficient for the RTC-S1 jobs to run to completion.
@gshiroma If you could review the changes to …
=> DEM from bounding box margin fix

opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/opera_chimera/test_precondition_functions.py
This branch adds a feature to automatically disable static layer generation for the R2 PGE's whenever the processing mode is not set to "forward". This ensures that static layers are never generated when in "historical" or "reprocessing" mode.
This branch was tested by using the daac_data_subscriber.py script with the `--processing-mode=historical` option, and with static layers enabled for CSLC-S1 in settings.yaml. Within the `run_sciflo_L2_CSLC_S1.log` file for the job, the following should appear near the top of the log:
```
2023-07-20 21:38:19 opera_pcm:INFO [precondition_functions.py:765] Getting ENABLE_STATIC_LAYERS setting for PGE CSLC_S1
2023-07-20 21:38:19 opera_pcm:INFO [precondition_functions.py:773] Processing mode for L2_CSLC_S1 is set to historical, static layer generation …
```
=> Static layer toggle for historical processing

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L2_CSLC_S1.yaml, conf/schema/RunConfig_schema.L2_RTC_S1.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist, docker/job-spec.json.SCIFLO_L2_RTC_S1, opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1.yaml, opera_chimera/configs/pge_configs/PGE_L2_RTC_S1.yaml, opera_chimera/precondition_functions.py, tests/opera_chimera/test_precondition_functions.py, tests/util/test_pge_util.py, util/pge_util.py
This branch updates PCM to incorporate v2.0.0-rc.2.1 of the R2 PGEs (CSLC-S1 and RTC-S1). Major changes with this release include updates to the file naming conventions for both baseline and static layer products, as well as changes to the workflow such that only the baseline products or static layer products can be produced at a time.
This branch was tested with the R2 PGEs both in simulation and real mode using the following input SLC archive:
S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC
For real mode, both the baseline and static layer workflows were tested by setting the `enable_static_layers` flag appropriately in settings.yaml.
Lastly, this branch also introduces a fix for #574 so that simulation mode products always use the current time for the production …
=> R2 PGE v2.0.0-rc.2.1 Integration

tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
This branch updates stage_orbit_file.py to ensure the selected Orbit file has a start time that occurs at least 60 minutes prior to the start time of the corresponding SLC SAFE archive. This change is to bring the staging logic in line with what is expected by the s1_reader library utilized by the R2 SAS.
=> Orbit time range start margin fix

opera_chimera/precondition_functions.py, tests/util/test_pge_util.py, tools/stage_ionosphere_file.py, wrapper/pge_functions.py
This branch updates the stage_ionosphere_file.py script to support the new file naming conventions adopted after 8/12/2023 (?). The script will attempt to look for the "legacy" ionosphere file name, and if it is not available (provider returns 404 code), then it will reattempt using the "new" naming conventions. If the file still cannot be found, the `IonosphereFileNotFoundException` error will be raised.
The changes to stage_ionosphere_file.py were tested locally with the following granules:
- Legacy: `S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC`
- New: `S1A_IW_SLC__1SDV_20230812T170353_20230812T170419_049845_05FEAE_1474`
- Invalid (no ionosphere files available yet): `S1A_IW_SLC__1SDV_20230816T170353_20230816T170419_049845_05FEAE_1474`
Note that the Invalid case …
=> Ionosphere naming convention update

data_subscriber/download.py, data_subscriber/hls/hls_catalog.py, data_subscriber/slc/slc_catalog.py
- When downloading just one granule by native-id, this changes makes it much for efficient
- [CHANGE] In download code 
- https://github.com/nasa/opera-sds-pcm/issues/500
- Tested both HLS and SLC download and SCIFLO execution for both native-id and traditional date range queries. All passed.
=> Issue 500 batch id 1

tools/ops/cmr_audit/cmr_audit_hls.py, tools/ops/cmr_audit/cmr_audit_slc.py
- cmr_aduit report name contains duplicate timestamp and missing start timestamp
https://github.com/nasa/opera-sds-pcm/issues/609
=> Fix incorrect start time on the report name

cluster_provisioning/modules/common/main.tf
update runtime ahead of deprecation scheduled for 1/2024 by AWS
- update runtime ahead of deprecation. 
- [CHANGE] runtime used by harikiri lambda
- issue-617
- tested on int environment
=> issue 617: chore(terraform): update python runtime for harikiri lambda

conf/settings.yaml, tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
- This branch addresses an issue in the stage_orbit_file.py script where the initial query time range was set up incorrectly, leading to potential orbit file candidates being missed.
- This branch also corrects the estimated geometric accuracy values defined in settings.yaml
- Fixes #620 
- Fixes #621 
- The fix to stage_orbit_file.py was tested with the following SLC granules that require concatenated RESORB files:
```
S1A_IW_SLC__1SDV_20230823T154843_20230823T154910_050004_060418_D30E.zip
S1A_IW_SLC__1SDV_20230823T154908_20230823T154935_050004_060418_521B.zip
S1A_IW_SLC__1SDV_20230823T154933_20230823T155000_050005_060418_42A5.zip
S1A_IW_SLC__1SDV_20230823T154958_20230823T155034_050005_060418_8D51.zip
S1A_IW_SLC__1SDV_20230823T172819_20230823T172849_050006_060423_EEC4.zip …
```
=> Orbit script query range fix

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, docker/job-spec.json.SCIFLO_L2_RTC_S1
- This branch integrates v2.0.1 of the RTC-S1 PGE into PCM. This version incorporates the v1.0.1 point delivery of the RTC-S1 SAS to correct some metadata fields in the GeoTIFF
- Resolves #623 
- This branch was tested in a dev cluster configured to run only RTC-S1 PGE baseline workflow (not static layers). The granule used was S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC. Individual output products were inspected to ensure metadata fields such as static layer access URL and the estimated geometric accuracy values were set correctly.
=> RTC-S1 PGE v2.0.1 integration

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/pge_outputs.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/settings.yaml, docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC_hist, docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist, docker/job-spec.json.SCIFLO_L2_RTC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC, opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1_STATIC.yaml, opera_chimera/configs/pge_configs/PGE_L2_RTC_S1_STATIC.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/opera_pge_job_submitter.py, tests/util/test_pge_util.py, util/pge_util.py, wrapper/opera_pge_wrapper.py
- This branch integrates v2.1.0 of the R2 PGEs into PCM. This version incorporates the CSLC-S1 v0.5.4 Final SAS delivery, and removes the production datetime from the filenames of output static layer products.
- Additionally, this branch fixes an issue where the `INGEST_STAGED` flag in settings.yaml did not actually affect the use of no-clobber errors when uploading PGE outputs. Since we want redundant static layer products to be overwritten in S3, the default for `INGEST_STAGED` is now set to `True`
- Resolves #639 
- Branch was tested with a dev cluster by submitting the following granule for ingest: S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC
- Both R2 PGEs were run with both workflows (baseline and static)
- After all jobs completed successfully, the static …
=> R2 PGE v2.1.0 Integration

docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC_hist, docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist, docker/job-spec.json.SCIFLO_L2_RTC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC, docker/job-spec.json.SCIFLO_L3_DSWx_HLS
- This branch modifies the job-spec files for all PGE/SCIFLO jobs to enable the Hysds pre- and post-processing functions to perform parallelized localization and upload to S3. This has shown to be a significant improvement in runtime when uploading products to rolling storage.
- Resolves #645 
- Branch was tested on a dev cluster using hysds-framework v5.0.0-rc.1
- All R2 PGEs (baseline and static layers) were triggered on the following granule: `S1A_IW_SLC__1SDV_20220501T015035_20220501T015102_043011_0522A4_42CC`
- After PGE completion, parallel upload to rolling storage was visually confirmed by watching the rolling storage bucket from the AWS console
=> Enable parallelized localization/upload for PGE jobs

cluster_provisioning/dev-e2e-event-misfire/main.tf, cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/main.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/main.tf, cluster_provisioning/dev-releaser/main.tf, cluster_provisioning/dev-releaser/variables.tf, cluster_provisioning/dev-restore-snapshot/main.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/main.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/int/int-fwd/main.tf, cluster_provisioning/modules/common/mozart.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/ops-fwd/main.tf, conf/sds/files/netrc, conf/sds/files/netrc.mozart, conf/settings.yaml, data_subscriber/asf_download.py, tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
- This branch updates the stage_orbit_file.py script for compatibility with the new orbit file service, [Copernicus Data Space Ecosystem (CDSE)](https://dataspace.copernicus.eu/)
- Use of CDSE requires valid credentials for downloads (unlike scihub where we were using public guest credentials). To accommodate, the Terraform deployment scripts now expect a `dataspace_user` and `dataspace_pass` to be defined in the user's .tfvars file. Once this branch is merged, ensure that the correct credentials have been added to your .tfvars file before the next deployment. Values for the credentials have been provided via LFT.
- Resolves #651 
- This branch was tested on a dev cluster with the R2 PGE's running in real mode with the following granule: …
=> Orbit file service migration

cluster_provisioning/dev-e2e/variables.tf
- Remove blank default creds from variables.tf. These will let deployments success without necessary creds - and the system will fail while running. Better to catch these errors at deployment time.
=> Removing blank defaults for some credentials

data_subscriber/asf_download.py, data_subscriber/daac_data_subscriber.py, tools/stage_orbit_file.py
- This branch incorporates use of the `backoff` library to add backoff and retry logic to functions in `stage_orbit_file.py` which make HTTP requests to the orbit file service provider. Backoff/retry is implemented using a constant retry interval of 15 seconds, and a max wait time of 5 minutes. Backoff/retry will only occur when an HTTP request returns an HTTP error code indicating a transient error (ex: too many requests)
- This branch also fixes a few issues discovered during testing related to download of multiple RESORB files.
- Resolves #659 
- Branch was tested on a dev cluster by enabling the SLC download timer to simulate forward production. Since all changes were made to the download job, all PGE triggers were disabled for testing. Cluster was allowed to run overnight for two …
=> Backoff/retry for Orbit Staging

conf/pge_outputs.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg
- This branch fixes an issue where the shadow mask output file (ending in "_mask.tif") was being excluded mistakenly from RTC-S1 datasets uploaded to S3 (and subsequently published via CNM).
- The regex for RTC-S1 output products in pge_outputs.yaml has been corrected to include files ending in "_mask.tif"
- The regex for RTC-S1 datasets in datasets.json has been cleaned up to remove an unnecessary sub-pattern.
- Fixes #671 
- Branch was tested on a dev cluster by submitting a SLC download job to trigger an RTC-S1 SCIFLO job (not simulated). The mask file was confirmed to be present in datasets uploaded to S3 after job completion, as well as being included in the list of files sent in the CNM notify messages.
=> Fix for missing RTC Mask file

tools/stage_dem.py, tools/stage_worldcover.py
- This branch addresses the crashes reported in #684, where the Worldcover ancillary input would fail to stage for specific MGRS tiles. The stage_worldcover.py script now catches such errors, and falls back to using an "unadjusted" projection window, which has been shown to not cause the failure when called with `gdal.Translate()`. This was done to ensure that we use the same staging logic for all DSWx-HLS jobs that had previously worked, and only use this new logic for the very few tiles that exhibit this behavior.
- This branch also attempts to address #685. The root cause of this bug was a transient outtage of S3 availability, so to mitigate going forward, the `backoff` decorators used in `stage_dem.py` and `stage_worldcover.py` have been adjusted to wait a maximum of 10 minutes before …
=> Fix for Worldcover translation failure

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl, conf/schema/RunConfig_schema.L3_DSWx_S1.yaml, docker/hysds-io.json.SCIFLO_L3_DSWx_S1, docker/job-spec.json.SCIFLO_L3_DSWx_S1, opera_chimera/accountability.py, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, product2dataset/product2dataset.py, tests/opera_chimera/test_precondition_functions.py, tools/stage_ancillary_map.py, tools/stage_dem.py, tools/stage_worldcover.py, util/pge_util.py, wrapper/pge_functions.py
- This branch integrates v3.0.0-er.5.0 of the DSWx-S1 PGE with OPERA PCM. This release incorporates the beta v0.2.1 of the DSWx-S1 SAS.
- As part of this integration, support for staging all (current) ancillary file types has been added.
- Resolves #682 
- Similar to the previous integration, the DSWx-S1 PGE can be tested by invoking an on-demand job via the Tosca UI. No additional arguments are needed. In its current configuration, the DSWx-S1 SCIFLO job will read a JSON file from S3 containing a canned set of product metadata, such as would be produced by the actual DSWx-S1 trigger logic.
**NOTE**: To disable the use of this canned metadata, the following line should be removed from the DSWx-S1 chimera config: https://github.com/nasa/opera-sds-pcm/blob/issue_682_dswx_s1_er5.0_integration …
=> DSWx-S1 ER5.0 Integration

data_subscriber/rtc/rtc_job_submitter.py, docker/job-spec.json.rtc_query, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, opera_chimera/opera_pge_job_submitter.py, wrapper/opera_pge_wrapper.py
- This branch makes the minor modifications needed to integrate the RTC download/trigger logic with actual invocation of the DSWx-S1 PGE.
- Small modifications have been made to the product metadata provided by rtc_job_submittter.py to make it compatible with the chimera pre-condition functions for DSWx-S1
- The set_sample_product_metadata precondition for DSWx-S1 has been removed, so the metadata provided by rtc_job_submitter.py will be used instead.
- Additional directories have been added to the list of triaged locations to aide in debugging of runtime errors with the current DSWx-S1 SAS
- The time limit for RTC query/download jobs has been increased to 7200 seconds since the occasional time-out failure was observed during testing. This was usually during the initial download of all …
=> DSWx-S1 E2E Integration

cluster_provisioning/modules/common/launch_template_user_data.sh.tmpl, cluster_provisioning/modules/common/variables.tf, conf/sds/rules/user_rules.json, data_subscriber/rtc/mgrs_bursts_collection_db_client.py, docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC, docker/job-spec.json.SCIFLO_L3_DSWx_S1
- This branch fixes two issues, one for R2 processing and one for R3:
- For R2, this branch adds a new auto-scaling group queue specifically for RTC-S1-STATIC jobs, which utilize memory optimized instances instead of compute optimized. There were about 4 failures from static layer production which we caused by workers running out of available memory on compute optimized instances. By switching to memory optimized versions, the 4 jobs were all able to run to completion.
- For R3, this branch fixes the bug where the lat/lon bounding box extracted from the MGRS tile set database had coordinates swapped between lat and lon. Previously this caused nearly all DSWx-S1 jobs to fail since the DEM was staged incorrectly. With this fix, many more jobs are able to complete succesfully (only 4 …
=> R2/R3 Fixes

data_subscriber/asf_cslc_download.py, data_subscriber/cmr.py, data_subscriber/cslc/cslc_query.py, data_subscriber/cslc_utils.py, data_subscriber/daac_data_subscriber.py, data_subscriber/download.py, data_subscriber/query.py, data_subscriber/survey.py, docker/job-spec.json.cslc_query, docker/job-spec.json.cslc_query_frame_range, docker/job-spec.json.cslc_query_hist, tests/data_subscriber/test_cslc_query.py, tests/scenarios/cslc_query_fwd_test.py
This doesn't yet have anything about the triggering grade period logic yet. Instead, it **fixes various DISP S1 historical processing. All known issues have been resolved**:
1. CSLC Historical Query was failing in general because the batch id is in different form than in forward processing. This is now handled.
2. CSLC Historical Query was incorrectly sending all download batches to a single download job. This was incorrect. It now generates one download job per download batch, which maps to a complete frame.
3. CSLC Download now deletes local files after they are uploaded to S3 RS so that it doesn't run out of local space.
4. Query soft timer has been doubled. This should suffice for all cases w frame range of 100 or less unless CMR has major slow down - in which case the query can be …
=> DISP S1 Historical Processing Fixes

data_subscriber/asf_cslc_download.py, data_subscriber/asf_download.py, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tools/stage_dem.py, tools/stage_ionosphere_file.py, wrapper/pge_functions.py
- This branch integrates support for download and staging of the DEM and Ionosphere ancillary input types with the DISP-S1 PGE workflow
- To resolve the current issue with frame IDs starting with "f", this branch cherry-picks commit 0923975b59af687665040a2156b3de0592fb0d45 from #735. If that branch is merged before this one, I will rebase this branch to ensure there are no conflicts.
- Resolves #736 
- This branch was tested on a dev cluster by submitting the following command to query/download CSLC-S1 products for a single DISP-S1 job:
```
python3 ~/mozart/ops/opera-pcm/data_subscriber/daac_data_subscriber.py query \
--collection-shortname=OPERA_L2_CSLC-S1_V1 \
--endpoint=OPS \
--k=4 \
--release-version=issue_736_disp_s1_initial_dynamic_ancillary_support \ …
```
=> DISP-S1 DEM/Ionosphere Ancillary Input Support

data_subscriber/asf_cslc_download.py, data_subscriber/cmr.py, data_subscriber/cslc/cslc_query.py, data_subscriber/cslc/cslc_static_catalog.py, data_subscriber/cslc/cslc_static_query.py, data_subscriber/cslc_utils.py, data_subscriber/daac_data_subscriber.py, data_subscriber/download.py, data_subscriber/parser.py, data_subscriber/query.py, data_subscriber/rtc/rtc_query.py, tests/data_subscriber/test_cslc_query.py, tests/scenarios/cslc_query_test.py, util/conf_util.py, wrapper/opera_pge_wrapper.py
- This branch updates the daac_data_subscriber tool to support query and download of CSLC-S1 Static Layer products for use with the DISP-S1 workflow.
- Query of CSLC-S1 Static Layer products works as normal from the command line, just use "OPERA_L2_CSLC-S1-STATIC_V1" as the collection name.
- Download of static layer products is **not** currently supported via the command line. Static layer products are only downloaded as part of the standard CSLC-S1 product download workflow.
- This branch also adds a significant amount of cleanup, refactoring and bug fixes to the data subscriber.
- Argument parsing code has been moved into its own parser.py module to cut down on  SLOC in the main daac_data_subscriber.py script
- Enumerations for commonly used string constants has been added to cmr.py …
=> CSLC-S1 Static Layer Query/Download Support

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L2_RTC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1_STATIC.jinja2.tmpl, docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC_hist, docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist, docker/job-spec.json.SCIFLO_L2_RTC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC, opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1.yaml, opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1_STATIC.yaml, opera_chimera/configs/pge_configs/PGE_L2_RTC_S1.yaml, opera_chimera/configs/pge_configs/PGE_L2_RTC_S1_STATIC.yaml, tests/opera_chimera/test_precondition_functions.py, wrapper/pge_functions.py
- This branch integrates v2.1.1 of the R2 PGEs (CSLC-S1 and RTC-S1). This delivery incorporates SAS Final point releases 6.4 (CSLC-S1) and 5.2 (RTC-S1).
- RunConfig templates for RTC-S1 and RTC-S1-STATIC have been updated to include the template version of the product access/static layer access URLs
- Support for handling the .sqlite extension has been added to the lineage metadata function for SLC products
- Fixed a broken unit test for the `get_disp_s1_frame_id` precondition function
- Resolves #772 
- Branch was tested using a dev cluster and running the RTC-S1 and CSLC-S1 workflows (including static layer generation) in both simulation and real mode. SLC query timer was enabled and cluster was allowed to run for about 2-3 hours, during which time all jobs completed successfully.
=> R2 PGE v2.1.1 Integration

tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
- This PR fixes a bug in stage_orbit_file.py where the giveup function, which determines whether an automatic retry should occur or not, was not implemented correctly. This resulted in Orbit file downloads failing after only a single transient error was encountered, rather than once every ~15 seconds until success or 5 minutes have elapsed.
- Fixes #796 
- A unit test has been added to test_stage_orbit_file.py which simulates all the transient error codes we check for during an orbit file download, and ensures that the download is retried for each failure code.
=> Orbit file script backoff/retry fix

report/dswx-s1-validator/README.md, report/dswx-s1-validator/dswx_s1_validator.py
- Update dswx-s1-validator code to address R3 calval use cases
- [ADD] endpoint option to specify OPS or UAT CMR venue
- [UPDATE] README to address new argument
- [UPDATE] README to fix iso timestamps in example
- Code has been used with R3 calval data
=> add uat option to validator script and document in readme

data_subscriber/rtc/evaluator_core.py
Refs #823
- keep evaluation constant in sync with mgrs tile db
- [CHANGE] keep evaluation constant in sync with mgrs tile db for better evaluation performance
- issue-823
=> feat(dswx-s1): update max burst length constant used in optimizing evaluator performance

report/dswx-s1-validator/README.md, report/dswx-s1-validator/dswx_s1_validator.py
- Support for a minimum matching burst count
- [ADD] New command-line argument to support
- [CHANGE] Filtering logic to support new argument
- [CHANGE] README directions for filtering
- N/A
- Tested successfully with the below case:
```
python dswx_s1_validator.py --start "2023-12-05T01:00:00Z" --end "2023-12-05T03:59:59Z" --db MGRS_tile_collection_v0.3.sqlite --threshold 50
Total granules: 2316
Querying CMR for time range 2023-12-05T01:00:00Z to 2023-12-05T03:59:59Z.
Fetching granules: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2316/2316 [00:04<00:00, 468.24it/s]
Granule fetching complete.
Calculating coverage: …
```
=> Added support for a minimum configurable matching burst count

data_subscriber/asf_cslc_download.py, data_subscriber/download.py
For CSLC burst and static file downloads if the protocol is not `https`, the download code will use the ASF S3 paths as the local storage and bypass the download. All other download functionality, including CSLC https download, have been preserved.
CSLC ionosphere files are only available via http so those are still downloaded.
This code has been tested with HLS, SLC, RTC, and CSLC S3 and https download/SCIFLO and all are working correctly.
=> 861 disp s1 use asf s3

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/unit/opera_chimera/test_precondition_functions.py
- This branch integrates DISP-S1 PGE v3.0.0-rc2.2 with OPERA PCM. This version wraps the v4.2 delivery of the corresponding SAS, and fixes several issues related to use of CSLC products that have file name conventions already applied.
- This branch also introduces a fix for #827 such that the chimera workflow for DISP-S1 determines the correct polarization to assign into the algorithm parameters runconfig, based on the polarization of the input CSLC products.
- Resolves #858 
- Fixes #827 
- Unit tests for OPERA precondition functions have been updated to accommodate changes to algorithm parameter runconfig instantiation
- This branch was tested on a dev cluster with the following commands:
- General DISP-S1 test: `python3 ~/mozart/ops/opera-pcm/data_subscriber/daac_data_subscriber.py …
=> DISP-S1 v3.0.0-RC2.2 Integration

cluster_provisioning/modules/common/variables.tf, data_subscriber/parser.py, docker/hysds-io.json.cslc_download, docker/job-spec.json.cslc_download, docker/job-spec.json.cslc_download_hist
CSLC download job now accepts --processing-mode as a parameter. Query job already passes --processing-mode parameter when submitting download jobs so it did not require changing.
=> #896: CSLC download job now accepts --processing-mode as a parameter

cluster_provisioning/modules/common/launch_template_user_data.sh.tmpl, cluster_provisioning/modules/common/variables.tf, docker/hysds-io.json.pge_smoke_test, docker/job-spec.json.pge_smoke_test, pge_smoke_test/run_pge_smoke_test.sh
- This branch adds a new on-demand job type to Tosca for executing the PGE/SAS integration test within an OPERA SDS context. The integration test is the same as is run in the PGE Jenkins system, and includes a step for comparing output products to a set of expected "golden" outputs downloaded from S3.
- When configuring the on-demand job, the only required fields are the PGE type (from a dropdown menu) and a name of an S3 bucket to push the test results to:
- Currently, only the R3 PGEs (DSWx-S1 and DISP-S1) are available. The R1 and R2 PGEs will be supported once new releases are approved via the OPERA Change Control Board.
- Once a smoke test has completed, the results are uploaded to the specified S3 bucket (barring any permission issues), within a `smoke_test/<pge_name>/<pge_version>` …
=> PGE Smoke Test On-Demand Job

report/dswx-s1-validator/README.md
- There was a bug previously that made it so that validation only provided accurate results if threshold == 100. This fixes that.
- The PR includes a complete rewrite of the validation logic: instead of using MGRS Tile IDs for validation, it uses RTC Burst ID matching. The logic works like this:
1. RTC bursts are queried at CMR between a start and end date
2. DSWx-S1 tiles are queried for at CMR between the same start and end dates
3. A list of input RTC bursts used for the DSWx-S1 tiles are extracted and aggregated
4. Lists 1 and 3 are compared for differences. If differences are found, a report table is generated detailing MGRS Tile ID, covered RTC burst IDs, and missing / unprocessed RTC burst IDs.  
- [CHANGE] Fixes to script to use RTC burst ID based validation
- #888 
- Tested …
=> Fixed validation bug

conf/RunConfig.yaml.L3_DISP_S1.jinja2.tmpl, conf/pge_outputs.yaml, data_subscriber/asf_cslc_download.py, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, product2dataset/product2dataset.py, tests/unit/util/test_pge_util.py, tools/stage_ionosphere_file.py, util/pge_util.py, wrapper/pge_functions.py
- This branch incorporates usage of the the list of Compressed CSLC products provided to a DISP-S1 SCIFLO job. In addition to including the CCSLCs in the RunConfig for a DISP-S1 job, this branch also adds the following:
- CSLC download job now obtains the Ionosphere file(s) corresponding to the reference date of the CCSLCs to be used.
- Fixed a bug where the incorrect S3 URLs where assigned to the ES metadata for Compressed CSLC products
- The DISP-S1 workflow now utilizes the `save_compressed_slcs` flag provided to the job to assign the same field within the RunConfig
- Simulation mode for DISP-S1 now generates a realistic number of Compressed CSLC products (27), and the sample filenames have been updated to be more realistic to the actual workflow.
- Resolves #911 
- Branch has been …
=> DISP-S1 PGE Workflow Compressed CSLC Support

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl, conf/schema/RunConfig_schema.L3_DSWx_S1.yaml, docker/job-spec.json.SCIFLO_L3_DSWx_S1, docker/job-spec.json.pge_smoke_test, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py
- This branch integrates the DSWx-S1 PGE v3.0.1 with OPERA PCM. This release incorporates the Final v1.1 delivery of the corresponding SAS, which corrects an issue where the SAS could produce the incorrect MGRS tile set for certain regions of the globe.
- Resolves #957 
- Branch has been tested on dev cluster, specifically to test the fix for MGRS tile set generate describe above. The following commands were used to verify the fix:
- `python3 ~/mozart/ops/opera-pcm/data_subscriber/daac_data_subscriber.py query     --collection-shortname=OPERA_L2_RTC-S1_V1     --endpoint=OPS   --job-queue=opera-job_worker-rtc_data_download     --chunk-size=1     --transfer-protocol=auto     --native-id=OPERA_L2_RTC-S1_T114-243333-IW1_20240728T122706Z_20240728T164508Z_S1A_30_v1.0`
- This job should now …
=> DSWx-S1 PGE v3.0.1 Integration

opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml
- This branch disables inclusion of the water mask used with a DISP-S1 job, since the format of the existing water mask seems to be incorrect.
- Branch has been tested on a dev cluster to ensure that a DISP-S1 job can get up and running without the water mask present in the RunConfig
=> Disable inclusion of water mask with DISP-S1 workflow

data_subscriber/cslc_utils.py, data_subscriber/survey.py
```daac_data_subscriber``` ```survey``` for CSLC data can now survey for a specific DISP-S1 frame only.
=> 971 survey disp s1 frame only

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DSWx_NI.jinja2.tmpl, conf/schema/RunConfig_schema.L3_DSWx_NI.yaml, docker/job-spec.json.SCIFLO_L3_DSWx_NI, docker/job-spec.json.pge_smoke_test, opera_chimera/configs/pge_configs/PGE_L3_DSWx_NI.yaml, opera_chimera/precondition_functions.py, wrapper/pge_functions.py
- This branch integrates the DSWx-NI PGE v4.0.0-er.3.0 with OPERA PCM
- This release incorporates the beta delivery of the DSWx-NI SAS
- The method for executing this PGE has not changed since the previous version. It can be run by submitting an on-demand SCIFLO_L3_DSWx_NI job via Tosca, and will use the latest sample data provided with the beta SAS delivery.
- Resolves #994 
- Branch has been tested on a dev cluster by submitting a SCIFLO_L3_DSWx_NI job using both real and simulated PGE mode
- The on-demand PGE smoke test was also run using the AMD-based worker queue. All product comparisons passed.
=> DSWx-NI v4.0.0 er.3.0 Integration

data_subscriber/rtc/rtc_catalog.py, tests/unit/conftest.py, tests/unit/data_subscriber/test_catalog.py
Refs #1005
mitigate AttributeError in Jenkins
- [CHANGE] import and mocking of mgrs burst collection database
- #1005 
=> feat(opensearch): remove mock that breaks unit tests

docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC, docker/job-spec.json.SCIFLO_L2_CSLC_S1_STATIC_hist, docker/job-spec.json.SCIFLO_L2_CSLC_S1_hist, docker/job-spec.json.SCIFLO_L2_RTC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1_STATIC, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, docker/job-spec.json.SCIFLO_L3_DSWx_NI, docker/job-spec.json.SCIFLO_L3_DSWx_S1, opera_chimera/run_sciflo.py, opera_chimera/run_sciflo.sh
- This PR adds OPERA-specific versions of the `run_sciflo.sh` and `run_sciflo.py` entrypoint scripts which are normally part of the baseline `chimera` library. Our versions add support for supplying the soft timeout limit from our job-spec files to the Sciflo executor script, so that we override the default timeout of 24 hours.
- All job spec files for PGE Sciflo jobs have been updated to use our version of `run_sciflo.sh` as the entrypoint script.
- Resolves #1031 
- Changes to PGE Sciflo jobs have been tested on a dev cluster by running the PGEs in simulation mode. Inspection of the `run_sciflo_<PGE name>.log` files shows that the timeout value from the job-spec file is now propagated to the call to `sflExec.py`
For DISP-S1:
For DSWx-HLS:
=> Add support for propagation of soft time out to Sciflo worker

product2dataset/product2dataset.py
Reduces great amount of DISP-S1 and Compressed CSLC products metadata that makes way into the GRQ ES. Both of these indices must be stored perpetually in GRQ so data size minimization is paramount.
These changes reduce the size of a single DISP-S1 product ES document size by 80-90% (1mb to 100-200kb) and for Compressed CSLC by 60-80% (100kb to 20-40kb) Will have exact numbers once we perform an INT test.
=> 1035 reduce disp s1 product metadata grq

tools/ops/cmr_audit/cmr_audit_hls.py, tools/ops/cmr_audit/cmr_audit_slc.py
query version 1.1 for CSLC. use temporal time instead of native-id query.
- [CHANGE] use more efficient query after meeting with CMR ops team.
Refs #1041
Tested locally
=> issue 1041: feat(audit): query improvements

data_subscriber/asf_cslc_download.py, data_subscriber/asf_rtc_download.py, data_subscriber/daac_data_subscriber.py, data_subscriber/download.py, data_subscriber/parser.py, data_subscriber/rtc/rtc_query.py
- This branch introduces some light refactoring of the code used for RTC-S1 product download and DSWx-S1 job triggering. The primary goal is to consolidate all RTC download code to the `AsfDaacRtcDownload` to make the class more suitable for future extension and reuse when download/triggering is implemented for DSWx-NI.
- The `run_rtc_download` function (and associated helper functions) within `daac_data_subscriber.py` has been refactored into the `run_download` implementation within the `AsfDaacRtcDownload` class. This also simplifies the logic of the factory functions within `daac_data_subscriber.py`
- The superclass call to `DaacDownload.run_download()` in `AsfDaacCslcDownload.run_download()` has been modified to bypass the version now implemented in `AsfDaacRtcDownload`
- The `--file` …
=> Data Subscriber RTC Download Code Refactor

tools/ops/cmr_audit/cmr_audit_batch.py, tools/ops/cmr_audit/cmr_audit_hls.py, tools/ops/cmr_audit/cmr_audit_slc.py, tools/ops/cmr_audit/cmr_audit_utils.py
This PR is meant to improve the usability of cmr_audit.py in the following respects:
- Support the ability to run for a long date-time interval, but break up the queries in N days each
- Fix the current bug in the bounding box (missing SLC inputs are currently found in Antartica, i.e. the script returns false positives)
- Have the ability to disable CSLC or RTC accountability (to run faster)
- Add a newline at the end of the output files, to allow easy concatenation
- [ADD] A new cmr_audit_batch.py script to execute cmr_audit_X.py in chunks of N days
- [CHANGE] Refactor some of the functionality to prevent repetition of code
- [FIX] Bounding box that exclude Antartica from the query region
- https://github.com/nasa/opera-sds-pcm/issues/1054
- I have been using the modified version of the …
=> Improve CMR audit capabilities

conf/sds/files/celeryconfig.py.tmpl.asg, conf/settings.yaml, opera_chimera/precondition_functions.py
- This PR addresses two tickets at once: 1076 and 1077. I put them into one branch for quicker testing because time is of essence for these changes today.
- Change back `task_acks_late` to be `True`
- Parameterize num process determination for DISP-S1 SCIFLO PGE
- https://github.com/nasa/opera-sds-pcm/issues/1076
- https://github.com/nasa/opera-sds-pcm/issues/1077
- I ran DISP-S1 with n_procs = 9 instead of 17 we'd been using. Idea is to reduce the number of processes to reduce memory usage so that we are not thrashing on swap memory. I wanted to make sure that taking that approach wouldn't slow us down. It actually seems to have improved running time on average by 5%. There is some randomness to it but there is overall trend. Run time is in seconds. The run-time also encompasses ALL …
=> 1076 1077 disp s1 sciflo num processes and asg celery late ack

cluster_provisioning/modules/common/asg.tf
For ease of getting billed cost data for the job worker instances, add a cost allocation tag to the ASGs that propagate to them. This should allow easy filtering of costs due to workers
None done yet, but could test deploy to test dev cluster if desired
=> Add tag to worker instances to filter for them in cost queries

tools/fix_disp_s1_iso_xml_from_s3.py
- Tool to fix already-produced disp s1 iso.xml file in-place in S3
- New file
- https://github.com/nasa/opera-sds-pcm/issues/1088
- Ran this tool on the PST venue on ~8000 already-produced DISP-S1 iso.xml files and modified them in place in S3. Ran cnm and the products were accepted by ASF.
=> #1088: Tool to fix already-produced disp s1 iso.xml file in-place in S3

cluster_provisioning/modules/common/variables.tf, data_subscriber/asf_cslc_download.py, data_subscriber/cmr.py, data_subscriber/parser.py, docker/job-spec.json.cslc_download, docker/job-spec.json.cslc_download_hist, util/job_submitter.py
- Eliminated the rare cases of duplicate DISP-S1 SCIFLO job triggering by formulating custom payload_hash in the CSLC download job.
- Fixed CSLC-STATIC query issue that was introduced as a side-effect of another bug fix.
- Vastly optimized CSLC download code and reduced the run-time from 40 mins to 6 mins. Reduced the EC2 instance size to lower per hour cost from up to 20 cents to 2 cents. Reduced unnecessarily large EBS provision.
- https://github.com/nasa/opera-sds-pcm/issues/1095
- https://github.com/nasa/opera-sds-pcm/issues/1096
- Ran HLS, SLC, RTC forward timer over 12 hrs to process all.
- Been running DISP-S1 historical processing on frames `11115` and `11116` over 24 hrs and will continue to run over the weekend
=> 1095 1096 cslc download fixes

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/settings.yaml, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, docker/job-spec.json.pge_smoke_test, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/unit/opera_chimera/test_precondition_functions.py
- This branch integrates the DISP-S1 PGE v3.0.3 with OPERA-PCM. This version incorporates the SAS "final" delivery v0.5.4.
- Additionally, this branch adds the ability to specify S3 paths to the static ancillary inputs used by DISP-S1 within settings.yaml
Note that the parameters related to calculating the number of cores/threads to use for a DISP-S1 job have also been moved under the `DISP_S1` key to keep things organized.
- Resolves #1100
- Unit tests have been added to test the ability to pull S3 paths from settings.yaml for certain precondition functions
- This branch has been deployed on a dev cluster and tested using the DISP-S1 PGE in both simulation and real mode.
- The PGE integration smoke test for DISP-S1 was also run
To trigger test DISP-S1 jobs, the sample **historical** …
=> DISP-S1 PGE v3.0.3 Integration

tools/testing/validate_cslc_downloads.py
- This is a quick and independent tool used to validate `run_disp_s1_historical_processing.py` job submission for the entire sensing datetime space for a specific set of frames.
=> Tool to validate the job end result of historical cslc download jobs

cluster_provisioning/modules/common/variables.tf, data_subscriber/asf_cslc_download.py, data_subscriber/cslc/cslc_query.py, data_subscriber/cslc_utils.py, tests/data_subscriber/test_cslc_util.py, tools/disp_s1_burst_db_tool.py, tools/run_disp_s1_historical_processing.py
- Fixes for #1080
- Fixes for #1102
- Increased the machine sizes for CSLC query and download jobs because often the Sentinel1 process would take up an entire CPU core and not leave much for the actual functionality
- Tuned ASG for query and download jobs to make sure that query and download jobs aren't the bottleneck in processing when processing Priority 4 frames.
- https://github.com/nasa/opera-sds-pcm/issues/1080
- https://github.com/nasa/opera-sds-pcm/issues/1102
- Ran through the entire DISP-S1 Priority 1 Frames running query and download job and verified that all were successful.
- Ran the first set of processing for Priority 4 Frames which is the largest with ~800 frames. 
- Noticed that dev-sized GRQ ES …
=> DISP-S1 historical processing query and download job final improvements

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/settings.yaml, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, docker/job-spec.json.pge_smoke_test
- This branch integrates the DISP-S1 PGE v3.0.4 with OPERA-PCM. This version incorporates the SAS "final" delivery v0.5.5.
- Resolves #1110 
- Unit tests have been added to test the ability to pull S3 paths from settings.yaml for certain precondition functions
- This branch has been deployed on a dev cluster and tested using the DISP-S1 PGE in both simulation and real mode.
- The PGE integration smoke test for DISP-S1 was also run
To trigger test DISP-S1 jobs, the sample historical commands from the [wiki](https://wiki.jpl.nasa.gov/display/operasds/DAAC+Data+Subscriber+Real+Usage+Examples) should be utilized.
=> DISP-S1 PGE v3.0.4 Integration

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/settings.yaml, docker/Dockerfile, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, docker/job-spec.json.pge_smoke_test
- This PR integrates the DISP-S1 PGE v3.0.5 release with the v0.5.7 version of the DISP-S1 SAS
- Closes #1122 
- Deployed test cluster
- Ran smoke test
- Ran PGE in simulation mode
- Ran PGE in real mode with 2 consecutive CSLC queries (an earlier attempt did fail due to user error)
=> DISP-S1 v3.0.5 Integraion

.gitignore, conf/AlgoParams.yaml.L3_DISP_S1.jinja2.tmpl, conf/AlgoParams.yaml.L3_DSWx_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_CSLC_S1_STATIC.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1_STATIC.jinja2.tmpl, conf/RunConfig.yaml.L3_DISP_S1.jinja2.tmpl, conf/RunConfig.yaml.L3_DISP_S1_STATIC.jinja2.tmpl, conf/RunConfig.yaml.L3_DIST_S1.jinja2.tmpl, conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl, conf/RunConfig.yaml.L3_DSWx_NI.jinja2.tmpl, conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl, conf/schema/AlgoParams_schema.L3_DISP_S1.yaml, conf/schema/AlgoParams_schema.L3_DSWx_S1.yaml, conf/settings.yaml, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, util/conf_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- To address an issue with how an Algorithm Parameters config can sometimes reference another static ancillary input (such as a parameters override config), this branch reworks how Algorithm Parameters are instantiated from template to bring them in line with how the baseline RunConfig is generated. Currently, this only affects the DSWx-S1 and DISP-S1 PGE workflows.
- Rather than download a simple find/replace template for algo params from S3, there are now Jinja2 templates for them within the `conf` directory, as well as the corresponding Yamale schemas to verify contents of an instantiated template within PCM.
- The algo param templates are instantiated using the values derived from `opera_chimera` precondition functions in the same way as the baseline RunConfig
- The path to the …
=> Jinja2 Templates for Algorithm Parameters Config

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/pge_outputs.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/settings.yaml, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_STATIC, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, docker/job-spec.json.pge_smoke_test, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, tests/unit/util/test_pge_util.py, tools/stage_ionosphere_file.py, util/pge_util.py
- This branch integrates the DISP-S1 PGE v3.0.6 with OPERA PCM. This version continues to wrap the previous SAS delivery, but incorporates the DISP frame number into the output Compressed-CSLC file names to avoid potential collisions when adjacent frames share an input CSLC burst.
- Resolves #1156 
- Branch has been tested on a dev cluster by running the following:
- DISP-S1 PGE workflow using simulation mode
- DISP-S1 PGE workflow using real mode
- DISP-S1 PGE smoke test
- Changes to the CCSLC output file name has been visually inspected in S3 and within the ES index for CCSLC products:
In S3
In ES
=> DISP-S1 PGE v3.0.6 Integration
