nasa/opera-sds-pcm

.gitignore, Jenkins/e2e-opera-pcm-develop.sh, cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/modules/common/bash_profile.grq.tmpl, cluster_provisioning/modules/common/bash_profile.metrics.tmpl, cluster_provisioning/modules/common/bash_profile.mozart.tmpl, cluster_provisioning/modules/common/bash_profile.verdi.tmpl, cluster_provisioning/modules/common/main.tf
This PR addresses issue #37, adding a copy of the shell script used with Jenkins to perform nightly E2E test builds of the PCM cluster. Some needed fixes to the terraform scripts and related templates are also included.
Once this branch is merged, I will enable the E2E job to run nightly, and try to setup slack notifications.
=> Issue 37 PCM Nightly E2E Build Script

data_subscriber/catalog.py, data_subscriber/daac_data_subscriber.py, data_subscriber/daac_data_subscriber_download.sh, data_subscriber/daac_data_subscriber_query.sh
=> Issues 66 and 67

data_subscriber/catalog.py, data_subscriber/daac_data_subscriber.py, data_subscriber/daac_data_subscriber_download.sh, data_subscriber/daac_data_subscriber_query.sh
=> Revert "Issues 66 and 67"

conf/sds/rules/user_rules-cnm.json.tmpl
Modify user_rules-cnm.json.tmpl due to change for CamelCase -> snake_case migration in CNM_product_delivery repo
=> Modify user_rules-cnm.json.tmpl 

benchmark/README.md, benchmark/benchmark_test_util.py, benchmark/conftest.py, benchmark/test_benchmark.py, pytest.ini, setup.py
=> feat(benchmark): added benchmark load test utility

data_subscriber/daac_data_subscriber.py, data_subscriber/hls/hls_catalog.py
=> Handle zero undownloaded files in data subscriber index

cluster_provisioning/dev/main.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/variables.tf, data_subscriber/daac_data_subscriber.py, data_subscriber/hls/hls_catalog.py, data_subscriber/hls/hls_download.sh, data_subscriber/hls/hlsl30_query.sh, data_subscriber/hls/hlsl30_query_minutes.sh, data_subscriber/hls/hlss30_query.sh, data_subscriber/hls/hlss30_query_minutes.sh, docker/hysds-io.json.hlsl30_query, docker/hysds-io.json.hlsl30_query_minutes, docker/hysds-io.json.hlss30_query, docker/hysds-io.json.hlss30_query_minutes, docker/job-spec.json.hlsl30_query, docker/job-spec.json.hlsl30_query_minutes, docker/job-spec.json.hlss30_query, docker/job-spec.json.hlss30_query_minutes
Closes #68 and #102
See also: https://github.com/nasa/opera-sds-lambdas/pull/7
To test, use hysds_ui on demand job feature in browser. There are query jobs specifying datetime ranges or elapsed minutes for L30 and S30. There is a single download job for all HLS products.
I also included a bugfix for the granule processing which was the result of a typo.
=> Issue 68 and 102

cluster_provisioning/dev-e2e-baseline-pge/variables.tf, cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-releaser/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/main.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/variables.tf
Change cnm_r_event_trigger from sqs to sns
Add cnm_r_venue variable
=> issue_95: change sqs to sns

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_HLS.jinja2.tmpl, docker/Dockerfile, docker/hysds-io.json.hlsl30_query, docker/hysds-io.json.hlsl30_query_minutes, docker/hysds-io.json.hlss30_query, docker/hysds-io.json.hlss30_query_minutes, docker/job-spec.json.SCIFLO_L3_DSWx_HLS, opera_chimera/configs/pge_configs/PGE_L3_HLS.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/conftest.py, tests/opera_chimera/test_precondition_functions.py, tests/util/test_pge_util.py, tools/stage_dem.py, wrapper/opera_pge_wrapper.py
This PR adds the necessary precondition functions to stage a DEM for use with the DSWx-HLS PGE. The DEM region is cropped from the full DEM stored in S3, based on the tile code parsed from the input HLS dataset.
=> Issue 4 DEM Ingestion

cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/variables.tf, docker/job-spec.json.hls_download, docker/job-spec.json.hlsl30_query, docker/job-spec.json.hlsl30_query_minutes, docker/job-spec.json.hlss30_query, docker/job-spec.json.hlss30_query_minutes
=> Rename data subscriber queues to be HLS queues

tools/stage_worldcover.py
This PR fixes a bug in the `stage_worldcover.py` where, for certain HLS tiles, the region polygon used to obtain the worldcover region could be translated to polar coordinates unnecessarily. This would result in gdal thinking it needed an absurd amount of disk space to allocate the image.
To test that the fix works, you can use the `HLS.S30.T15XWM.2022198T215101.v2.0` dataset as input for a DSWx-HLS PGE job. A copy of the dataset can be found within the `opera-dev-lts-fwd-collinss` bucket, under the `products` key. This dataset had previously triggered the error condition fixed by this branch.
Fixes #147
=> Worldcover Staging Fix

README.md
We obviously need a more detailed README, but for now, let's at least create a simple description for our users.
=> Explain PCM meaning

data_subscriber/daac_data_subscriber.py
=> Remove scroll param which broke search after

tools/README.md, tools/audit.py
=> feat(tools): adding script to verify system input and output products

.gitignore, cluster_provisioning/pst/main.tf, cluster_provisioning/pst/override.tf, cluster_provisioning/pst/variables.tf, cluster_provisioning/pst/versions.tf
Creating a sub cluster provisioning folder for pst
=> Cluster provisioning pst

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev/main.tf, cluster_provisioning/modules/common/outputs.tf, cluster_provisioning/run_opera_smoke_tests.sh, integration/conftest.py, integration/int_test_util.py, integration/test_integration.py
=> Issue 208: CSLC integration tests

extractor/extract.py, product2dataset/product2dataset.py, tests/extractor/test_extract.py, tests/product2dataset/test_product2dataset.py, util/conf_util.py
feat(ingest): added unit tests. added documentation comments. minor refactoring to aid in readability.
Refs #215
=> issue 215: data ingest as granule instead of individual files

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev/.terraform.lock.hcl, cluster_provisioning/int/variables.tf, cluster_provisioning/pst/variables.tf
=> Completing Issue 202 by adding pge_sim_mode to int and pst venues

tools/audit.py
improved logging. fixed debug log of variable.
Refs #244
=> issue 244: audit script improvements

product2dataset/product2dataset.py, util/datasets_json_util.py
=> Issue 243: PST metadata update

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/pst/override.tf, cluster_provisioning/pst/variables.tf
Reverts nasa/opera-sds-pcm#276
=> Revert "Issue 237"

data_subscriber/daac_data_subscriber.py, tests/data_subscriber/test_daac_data_subscriber.py
=> Simplify token handling

cluster_provisioning/modules/common/main.tf, data_subscriber/daac_data_subscriber.py, data_subscriber/slc/slc_download.sh, data_subscriber/slc/slcs1a_query.sh, data_subscriber/slc/slcs1b_query.sh, integration/README.md, integration/conftest.py, integration/subscriber_util.py, integration/test_integration.py, tests/data_subscriber/test_daac_data_subscriber.py
perform download+extract+ingest operations in same job. This includes bundling an orbit file with the dataset
=> Issue 278: SLC consolidated pipeline. orbit file download

data_subscriber/daac_data_subscriber.py
delete granule files after dataset directory creation
Refs #292
=> Issue 292: reduce disk utilization

data_subscriber/daac_data_subscriber.py
Merge issue_290 to 1.0.0-rc.6.0
=> Issue_290: feat(subscriber) - group by granule ID instead of tile ID

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/int/variables.tf, cluster_provisioning/modules/common/variables.tf, cluster_provisioning/ops/variables.tf, cluster_provisioning/pst/variables.tf, conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L2_CSLC_S1.yaml, conf/schema/RunConfig_schema.L2_RTC_S1.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1, extractor/extract.py, opera_chimera/configs/pge_configs/PGE_L2_CSLC_S1.yaml, opera_chimera/configs/pge_configs/PGE_L2_RTC_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/util/test_pge_util.py, util/pge_util.py, wrapper/pge_functions.py
This branch integrates the v2.0.0-er.5.0 releases of the R2 PGE's with OPERA PCM. This version incorporates the beta releases of the corresponding SAS images.
The instance types for the CSLC/RTC workers have been copied to match the DSWx instance types. The expected runtime for CSLC-S1 seems to be around 2 hours, for RTC-S1 it is closer to 3.5 hours.
=> R2 PGE ER5.0 Integration

integration/test_integration.py
=> feat(integration-tests): fix integration tests for new PGE release

cluster_provisioning/modules/common/variables.tf
=> issue 396: optimizing instance types. using c6i.2xlarge and c6a.2xlarge

conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl
=> issue 398: fix(slc): fix typo in RunConfig preventing CSLC jobs from running

tools/pcm_batch.py
=> Read .env file in pcm_batch.py

data_subscriber/daac_data_subscriber.py, data_subscriber/query.py
=> Exclude Antarctic region from bounding box in SLC queries

tools/stage_dem.py, tools/stage_worldcover.py, util/geo_util.py
Reverts nasa/opera-sds-pcm#419
=> Revert "Update `stage_dem.py` and `stage_worldcover.py` to properly handle the antimeridian crossing"

docker/job-spec.json.SCIFLO_L2_CSLC_S1, docker/job-spec.json.SCIFLO_L2_RTC_S1
=> issue 409: feature(SLC): update soft timeout limit to be tighter.

tools/audit.py
=> issue 447: feature(audit): update default time range

tools/audit.py
=> issue 449: feature(audit): timerange can be input as command args.

integration/subscriber_util.py
=> feature(test): fix integration tests for SLC.

data_subscriber/daac_data_subscriber.py
Addresses Cumulus bug that breaks Basic Auth for s3 credentials retrieval
=> LP Token Patch

tools/cmr_audit/cmr_audit_slc.py
=> feature(audit): added temporal filter to output query

tools/ops/es_query_executor/README.md, tools/ops/es_query_executor/queries/task_status-current/resources_old.json
- Ensure all clean up policies are using 14 days minimum retention period. 
- [CHANGE] resources.yml policy
- [CHANGE] README.md
N/A
N/A
=> All ES cleanup policies should have minimum 14 days doc retention

setup.py, tools/ops/README.md, tools/ops/cmr_audit/cmr_audit_hls.py, tools/ops/cmr_audit/cmr_audit_slc.py, tools/ops/cmr_audit/cmr_audit_utils.py
broken imports caused by file tree reorganization
Refs #513
=> issue 513: fix(tools): fix broken imports. fix setup.py. update README.md

tests/tools/test_stage_orbit_file.py, tools/stage_orbit_file.py
This branch addresses an issue where an orbit file could be selected by stage_orbit_file.py whose validity time range did not fully envelop the validity time range of the corresponding SLC SAFE archive.
stage_orbit_file.py now iterates over all results from the query, and selects the first orbit file whose validity time range fully envelops the SAFE time range.
This branch was tested on a dev cluster with the following SLC archive:
S1A_IW_SLC__1SDV_20210601T225942_20210601T230009_038153_0480C6_BB00
Both the RTC-S1 and CSLC-S1 jobs should now obtain the correct orbit file and complete successfully.
=> Orbit file selection fix

tools/ops/README.md, tools/ops/cmr_audit/cmr_audit_hls.py, tools/ops/cmr_audit/cmr_audit_slc.py, tools/ops/cmr_audit/cmr_audit_utils.py, tools/ops/cmr_audit/cmr_client.py
- To introduce concurrency control in the `cmr_audit_hls.py` script by adding a semaphore
- To share more details about dependencies being installed within the README 
- [CHANGE] Introduced a semaphore in `cmr_audit_hls.py` to control concurrent async tasks
- [CHANGE] Updated the pip installation command in `README.md` by adding the `-e` flag to enhance clarity and accuracy
- #590 
- The changes have been reviewed and tested locally without significant timeouts
- Further testing should be performed by OPS
=> Issue 590: CMR 504 timeout responses

cluster_provisioning/modules/common/variables.tf
- Update AMIs with latest version that was created on 09-15-23
- Change the AMIs with latest version
=> Update AMIs with a version created on 09-15-23

cluster_provisioning/modules/common/variables.tf
Reverts nasa/opera-sds-pcm#613
=> Revert "Update AMIs with a version created on 09-15-23"

cluster_provisioning/modules/common/variables.tf
- Update AMIs with latest version
=> Update AMIs with latest version

cluster_provisioning/dev-e2e-event-misfire/variables.tf, cluster_provisioning/dev-e2e-pge/variables.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev-restore-snapshot/variables.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/launch_template_user_data.sh.tmpl, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DSWx_S1.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/sds/rules/user_rules.json, conf/settings.yaml, docker/hysds-io.json.SCIFLO_L3_DSWx_S1, docker/job-spec.json.SCIFLO_L3_DSWx_S1, extractor/extract.py, opera_chimera/accountability.py, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, opera_chimera/precondition_functions.py, opera_chimera/wf_xml/L3_DSWx_S1.sf.xml, product2dataset/product2dataset.py, tests/util/test_pge_util.py, util/pge_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
This branch adds the initial integration of the DSWx-S1 PGE v3.0.0-er.4.0. Currently, the PGE can only be triggered manually through an on-demand Tosca job:
Note that this is an old screenshot and still shows the er2 branch
The current PGE job is configured to download and run with a set of sample inputs from S3 (from the collinss long term storage bucket). Simulation mode is also supported.
=> DSWx-S1 ER4 Integration

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/modules/common/mozart.tf, cluster_provisioning/modules/common/variables.tf
- Add sleep before sds update
- Update AMIs with 101523 version
=> Cluster provisioning fix 

cluster_provisioning/modules/common/mozart.tf, cluster_provisioning/modules/common/variables.tf, conf/sds/cluster.py, conf/sds/files/supervisord.conf.grq, conf/sds/files/supervisord.conf.metrics
=> Cluster provisioning fix

data_subscriber/daac_data_subscriber.py
Comment out exec_wrapper from daac_data_subscriber.py due to download job failure with exit code 1
=> Comment out exec_wrapper from daac_data_subscriber.py

data_subscriber/asf_download.py, tools/stage_orbit_file.py
- This branch updates `stage_orbit_file.py` to add a function which deletes an open authentication session with the Orbit file provider (CDSE) after completing an orbit file download. This was added to prevent leaving too many open sessions active at once and hitting the provider limit, resulting in 401 errors when attempting to authenticate.
- This branch also adds a backoff/retry decorator to `asf_download._get_aws_creds()` so the function can be automatically retried when the ASF authentication service returns transient 500 errors.
- Fixes #672 
- Branch was tested on a dev cluster configured to emulate the [Historical processing campaign performed during INT testing of R2.1.0](https://wiki.jpl.nasa.gov/pages/viewpage.action?spaceKey=operasds&title=R2+2.1.0+Testing+Configuration).
- …
=> Orbit Script Authentication Session Cleanup

data_subscriber/cmr.py, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/mgrs_bursts_collection_db_client.py, data_subscriber/rtc/rtc_catalog.py, docker/hysds-io.json.SCIFLO_L3_DSWx_S1, tools/stage_dem.py, util/aws_util.py
- to support executing dswx-s1 flow for the burst(s) a single RTC product is related to.
- [ADD] native-id query support
- issue-688
- tested locally and on personal dev cluster
=> Issue 688: native-id query support for RTC data retrieval

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/modules/common/outputs.tf, cluster_provisioning/run_opera_smoke_tests.sh, conf/settings.yaml, data_subscriber/asf_rtc_download.py, data_subscriber/download.py, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/evaluator_core.py, data_subscriber/rtc/evaluator_tool.py, data_subscriber/rtc/rtc_query.py, integration/README.md, integration/conftest.py, integration/subscriber_util.py, integration/test_integration.py, tests/data_subscriber/test_evaluator_core.py
- add support for rtc product collection grace period to maximize ingest before processing RTC product burst sets through DSWx-S1.
- [ADD] grace period for rtc product collection
- [ADD] integration tests
- issue-710
- Tested locally and on dev cluster
=> Issue 710: dswx-s1 ingest grace period

data_subscriber/asf_cslc_download.py, data_subscriber/cslc/cslc_query.py, data_subscriber/cslc_utils.py, data_subscriber/query.py, tests/scenarios/cslc_query_fwd_k2_test.json, tests/scenarios/cslc_query_fwd_test.py, tests/scenarios/cslc_query_reproc_k4_test.json
DISP-S1 Reprocessing query functionality. The user specifies one granule and k value. The code will query the corresponding granules from CMR to process all frames that fall in that granule-k criteria.
=> Disp s1 reprocessing

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DSWx_S1.yaml, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/job-spec.json.SCIFLO_L3_DSWx_S1, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, opera_chimera/constants/opera_chimera_const.py, opera_chimera/precondition_functions.py, tests/opera_chimera/test_precondition_functions.py, tests/util/test_pge_util.py, util/pge_util.py
- This branch integrates DSWx-S1 PGE v3.0.0-rc.1.0 with OPERA PCM
- This release of the DSWx-S1 PGE wraps the Gamma delivery of the associated SAS
- Updates to PCM code are mostly to accommodate the new output products created by the SAS (a DIAG layer tif, and the BROWSE png image)
- Resolves #720 
- This branch was tested on a development cluster, using the RTC query trigger to download RTC products and trigger the DSWx-S1 SCIFLO jobs. At time of creation of this pull request, about 40 DSWx-S1 jobs have successfully run to completion, with only 2 failures observed due to soft timeout limit.
=> DSWx-S1 RC1.0 integration

data_subscriber/rtc/evaluator_core.py
Refs #717
- improve logging. improve evaluator
- [ADD] logging of job submissions for easier troubleshooting
=> issue 717: feat(data-subscriber): improve logging. improve evaluator

data_subscriber/rtc/rtc_catalog.py, setup.py
- changes required for accountability
- [ADD] support for accountability
- issue-717
- tested on dev cluster and local environment
=> Issue 717: accountability changes

data_subscriber/cmr.py, tests/data_subscriber/test_cmr.py
Refs #739
- fix SLC query result filter
- [FIX] SLC query result filter
- issue-739
- unit tested on local environment
=> Issue 739: fix(data-subscriber): SLC URL filtered by IW

data_subscriber/daac_data_subscriber.py, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/rtc_query.py, integration/test_integration.py, tests/conftest.py, util/conf_util.py, util/ctx_util.py, util/os_util.py
- trigger logic tests for DSWx-S1
- [ADD] tests
- issue 725
- tested locally against dev cluster
=> Issue 725: additional integrations

cluster_provisioning/modules/common/query_timers.tf, data_subscriber/lpdaac_download.py, data_subscriber/url.py, docker/hysds-io.json.hls_download, docker/hysds-io.json.hlsl30_query, docker/hysds-io.json.hlsl30_query_minutes, docker/hysds-io.json.hlsl30_query_native_id, docker/hysds-io.json.hlss30_query, docker/hysds-io.json.hlss30_query_minutes, docker/hysds-io.json.hlss30_query_native_id, docker/job-spec.json.hls_download, docker/job-spec.json.hlsl30_query, docker/job-spec.json.hlsl30_query_minutes, docker/job-spec.json.hlsl30_query_native_id, docker/job-spec.json.hlss30_query, docker/job-spec.json.hlss30_query_minutes, docker/job-spec.json.hlss30_query_native_id
Enable https transfer mode for HLS data download
=> Hls viirs update

cluster_provisioning/modules/common/mozart.tf, data_subscriber/daac_data_subscriber.py, data_subscriber/query.py, data_subscriber/rtc/rtc_download_job_submitter.py, data_subscriber/rtc/rtc_job_submitter.py, data_subscriber/rtc/rtc_query.py, setup.py, tools/ops/README.md, tools/ops/data_subscriber/data_subscriber_client.py
Refs #725
- verification aid for DSWx-S1
- [ADD] tool for use in verifying DSWx-S1 behavior
- issue 717
=> Issue 737: utility for callling data subscriber for RTC

cluster_provisioning/run_opera_smoke_tests.sh, cluster_provisioning/run_opera_unit_tests.sh, data_subscriber/daac_data_subscriber.py, docker/Dockerfile, pytest.ini, tests/data_subscriber/test_cslc_query.py, tests/data_subscriber/test_daac_data_subscriber.py, tests/data_subscriber/test_query.py, tests/scenarios/cslc_query_test.py
- Updated unit tests that hadn't been maintained for a while and re-enabled them
- Adding cslc query scenario tests under integration test
=> Disp s1 integration test

cluster_provisioning/modules/common/mozart.tf
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> ES snapshot policy is now daily instead of hourly

data_subscriber/rtc/evaluator.py, data_subscriber/rtc/rtc_query.py
Refs #704
- handle test use case of native-id flow with lower coverage target. skip grace period logic for native-id
- [CHANGE] native-id flow to work with coverage target
- issue-780
=> fix(dswx-s1): native-id flow

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/modules/common/variables.tf, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/rtc_query.py
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Update amis 240315

conf/sds/files/supervisord.conf.mozart
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> #793: Halving the number of celery workers on Mozart

data_subscriber/rtc/evaluator.py, data_subscriber/rtc/mgrs_bursts_collection_db_client.py
Refs #788
- group bursts by all orbits they intersect
- [CHANGE] how bursts are grouped before evaluation
- Example: issue-788
- tested on local dev
=> issue 788: fix(dswx-s1): native-id flow to low coverage

product2dataset/iso_xml_reader.py, product2dataset/product2dataset.py, tests/product2dataset/test-files/OPERA_L3_DSWx-S1_T13UDU_20240314T130643Z_20240409T175743Z_S1A_30_v0.1.iso.xml, tests/product2dataset/test_product2dataset.py
Refs #785
- publish iso xml metadata to dataset
- [CHANGE] dataset to include iso xml metadata
- issue785
=> issue 785: feat(dswx-s1): publish iso xml metadata to dataset

cluster_provisioning/modules/common/query_timers.tf, data_subscriber/parser.py, data_subscriber/rtc/evaluator.py, docker/hysds-io.json.rtc_query
Refs #801
- filter out redundant catalog search results from DSWx-S1 evaluation
- [CHANGE] filter out redundant catalog search results from DSWx-S1 evaluation
-issue-801
=> issue 801: fix(dswx-s1): redundant rtc catalog results submitted for evaluation

commons/logger.py, data_subscriber/cmr.py, data_subscriber/daac_data_subscriber.py, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/rtc_query.py
Refs #787
- additional logging
- [CHANGE] logging for easier debugging and inspection
- issue-787
=> issue 787: feat(dswx-s1): additional logging

data_subscriber/cmr.py, data_subscriber/hls_spatial/hls_spatial_catalog.py, data_subscriber/slc_spatial/slc_spatial_catalog.py
Refs #829
- store additional timestamp for reporting accuracy
- [CHANGE] use additional datetime in accountability reports
- issue 829
tested locally
=> Issue 829: fix(accountability): prefer provider date time over production datetime

cluster_provisioning/modules/common/query_timers.tf, conf/settings.yaml, data_subscriber/parser.py, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/rtc_query.py, docker/hysds-io.json.rtc_query, docker/job-spec.json.rtc_query, tests/unit/data_subscriber/rtc/test_evaluator.py
Refs #837
minimum number of bursts required
- [ADD] coverage target as a minimum number of bursts
- issue-837
tested locally
=> Issue 837: feat(dswx-s1): use a count of bursts as the coverage target

cluster_provisioning/modules/common/cloudwatch.tf, cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/query_timers.tf
Refs #849
- optimize depends_on values
- [CHANGE] terraform scripts
issue-849
tested locally
=> Issue 849: feat(terraform): updated explicit depends_on values

tests/regression/test_dswx_s1_edge_cases.py
Refs #846
fix tests
- [CHANGE] 
issue-846
tested locally
=> Issue 846: feat(dswx-s1): update integration tests

cluster_provisioning/dev-releaser/create_releases.sh
- helper script for tagging releases
- [CHANGE] helper script for tagging releases
issue-825
Tested on CI/CD machine and locally.
=> Issue 825: opera release tagging

cluster_provisioning/modules/common/autoscaling_groups.tf, cluster_provisioning/modules/common/launch_template_user_data.sh.tmpl, data_subscriber/cslc/cslc_query.sh
Refs #853
fix logging config for RTC
- [CHANGE] logging config
issue-853
tested locally
=> Issue 853: fix(disp-s1): logging

data_subscriber/ionosphere_download.py
Refs #851
- traceability
- [CHANGE] record ionosphere download time
issue-851
tested locally
=> Issue 851: feat(cslc): ionosphere download ts record

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/launch_template_user_data.sh.tmpl, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DSWx_NI.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DSWx_NI.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/hysds-io.json.SCIFLO_L3_DSWx_NI, docker/job-spec.json.SCIFLO_L3_DSWx_NI, extractor/extract.py, opera_chimera/accountability.py, opera_chimera/configs/pge_configs/PGE_L3_DSWx_NI.yaml, opera_chimera/precondition_functions.py, opera_chimera/wf_xml/L3_DSWx_NI.sf.xml, product2dataset/product2dataset.py, tests/unit/product2dataset/test_product2dataset.py, tests/unit/util/test_pge_util.py, util/pge_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- This branch integrates the DSWx-NI PGE v4.0.0-er.1.0 with PCM
- For the current integration, the DSWx-NI PGE can be triggered as an on-demand job from Tosca
- The on-demand version of the job will download a set of "golden" inputs from S3
- Both simulation and real modes are supported
- Resolves #863 
- Resolves #873 
- Branch has been tested on a development cluster, in both real and simulated mode.
=> DSWx-NI ER 1.0 Integration

data_subscriber/rtc/evaluator.py
Refs #883
- improve dedupe to avoid redundant job submissions
- [CHANGE] improve dedupe to avoid redundant job submissions.
- issue-883
=> feat(dswx-s1): dedupe post-catalog query

CONTRIBUTING.md, data_subscriber/rtc/evaluator.py, data_subscriber/rtc/rtc_query.py, tests/unit/data_subscriber/rtc/test_evaluator.py
Refs #886
apply grace period for min-bursts scenario. revise logging.
- [CHANGE] logging. and apply grace period for min-bursts scenario.
- issue-886
- tested locally.
=> Issue 886: fix(dswx-s1): apply grace period for min-bursts scenario. revise logging

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/int_pst_ops_devcommon_override.tf, cluster_provisioning/modules/common/variables.tf
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Update branch version to 3.1.0-rc.3.0 and AMIs with 240615 version

data_subscriber/daac_data_subscriber.py, data_subscriber/rtc/rtc_job_submitter.py
Refs #901
- fix DSWx-S1 workflow
- [CHANGE] fix syntax errors. switch async logic to multithreading
-issue-901
=> Issue 901: fix(dswx-s1): fix job submissions broken after async refactor

tools/disp_s1_burst_db_tool.py
Add validation to the database tool. This will go through the entire cmr for each frame to make sure that the data that the database json claims actually exists
=> #898: frame acquisition cycle validation feature complete

cluster_provisioning/modules/common/variables.tf
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Use c7i & m7i EC2 types for DSWx-S1

data_subscriber/query.py, tests/tools/test_run_disp_s1_historical_processing.py, tools/README.md, tools/disp_s1_burst_db_tool.py, tools/pcm_batch.py, tools/run_disp_s1_historical_processing.py
Finalized version of batch processing application for DISP-S1 historical processing
=> 892 disp s1 historical batch processing

tools/ops/cmr_audit/cmr_audit_slc.py
update collection short name for CSLC and RTC.
removed collection_concept_id.
made chunk configurable.
added log-level param.
changed logger (name) used.
- [CHANGE] update collection short names.
- issue-912
=> Issue 912: fix(audit): update collection name used by cmr_audit

report/dswx-s1-validator/README.md, report/dswx-s1-validator/dswx_s1_validator.py
- Validator script changes to add post-generation CMR check for validating all DSWx-S1 tiles have been produced
- [CHANGE] Validator script, README
- #888 
- Local testing
- Tested validation for anomalous and nominal conditions (see README.md Usage section for details)
=> Code resolution for issue-888: dswx-validator report auditing feature

report/dswx-s1-validator/README.md, report/dswx-s1-validator/dswx_s1_validator.py
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Issue 888: dswx_s1 validator update

data_subscriber/rtc/rtc_download_job_submitter.py
- fix dedupe behavior when set coverage improves
- [CHANGE] payload to change when set coverage improves
Refs #939 
=> Issue 939: adjust hysds payload for proper deduping

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/modules/common/variables.tf
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Change AMIs with 240812 version

tools/disp_s1_burst_db_tool.py, tools/update_disp_s1_burst_db.py
This tool updates the disp-s1 database json file with the actual CSLC produced according to CMR
=> 943 disp s1 db update tool

cluster_provisioning/int_pst_ops_devcommon_override.tf, docker/job-spec.json.subsetter
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Update branch version to 3.1.0-rc.5.0

report/dswx-s1-validator/dswx_s1_validator.py
- Improvements and bug fixes to ensure the validator functions as expected for OPS and I&T use cases
- [CHANGE] UTC timestamp support for entering dates with a "Z" at the end
- [CHANGE] Fixed bug to include logic for gathering DSWx-S1 granules to support > 1000 use cases
- [CHANGE] Logic to ensure comparison of missing input RTC bursts includes only bursts that are missing for the given tile set, not all tile sets. This allows the validator to detect if we processed the wrong tile in cases where RTC bursts were used for multiple tile sets.
- N/A
- Tested locally
=> DSWx-S1 Validator Updates

data_subscriber/rtc/rtc_query.py, data_subscriber/url.py
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Change EPOCH from 20190101 to 20140101

ecmwf-api-client/run_merger_by_range_linux.sh, ecmwf-api-client/run_merger_by_range_macos.sh, ecmwf-api-client/run_subsetter_by_range_linux.sh, ecmwf-api-client/run_subsetter_by_range_macos.sh
Refs #914
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> fix(ecmwf): time range. password prompt

data_subscriber/cslc_utils.py, tests/data_subscriber/test_cslc_util.py, tools/disp_s1_burst_db_tool.py, tools/pcm_batch.py, tools/run_disp_s1_historical_processing.py, tools/view_pending_jobs.py
- Features useful for operator when historical processing DISP-S1
=> 997 disp s1 hist operator features

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, docker/job-spec.json.SCIFLO_L3_DISP_S1, docker/job-spec.json.SCIFLO_L3_DISP_S1_hist, docker/job-spec.json.pge_smoke_test, opera_chimera/accountability.py, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/opera_pge_job_submitter.py, opera_chimera/precondition_functions.py, product2dataset/product2dataset.py, util/pge_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- This branch integrates the DISP-S1 PGE v3.0.0-rc.4.1 with OPERA PCM
- This branch also adds a new function named `download_file_with_hysds()`, which wraps a call to `hysds.util.download_file` to add exponential backoff and retry for downloads performed while localizing input files during PGE initialization.
- Resolves #1007
- Fixes #1002 
- Branch has been tested on a dev cluster, running the DISP-S1 workflow in both simulation and real mode.
- Both forward and historical modes tested
- Reran PGE Integration Smoke Test, with all output products matching expected
=> DISP-S1 PGE v3.0.0 rc.4.1 Integration

cluster_provisioning/modules/common/grq_factotum_metrics.tf, report/dswx-s1-validator/README.md
Refs #1018
DSWx-S1 validator to metrics.
- [ADD] DSWx-S1 validator to metrics
#1018 
- tested on dev cluster
=> Issue #1018: feat(accountability): install DSWx-S1 validator tool on metrics.

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DIST_S1.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DIST_S1.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/hysds-io.json.SCIFLO_L3_DIST_S1, docker/job-spec.json.SCIFLO_L3_DIST_S1, extractor/extract.py, opera_chimera/configs/pge_configs/PGE_L3_DIST_S1.yaml, opera_chimera/precondition_functions.py, opera_chimera/wf_xml/L3_DIST_S1.sf.xml, product2dataset/product2dataset.py, tests/unit/util/test_pge_util.py, util/pge_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- This branch integrates the DIST-S1 PGE v6.0.0-er.1.0 with PCM
- This is a new PGE
- #1058 
- Unit test added for DIST-S1 simulation mode
- Successfully deployed PCM cluster and ran DIST-S1 job
=> DIST-S1 ER 1.0 Integration

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/main.tf, cluster_provisioning/dev-releaser/main.tf, cluster_provisioning/dev-releaser/variables.tf, cluster_provisioning/dev/main.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/modules/common/mozart.tf, cluster_provisioning/modules/common/variables.tf, conf/sds/files/netrc, conf/sds/files/netrc.mozart
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Add EARTHDATA_UAT_USER and EARTHDATA_UAT_PASS

data_subscriber/cslc_utils.py, tests/data_subscriber/test_cslc_util.py, tools/disp_s1_burst_db_tool.py, tools/pcm_batch.py, tools/run_disp_s1_historical_processing.py
- https://github.com/nasa/opera-sds-pcm/issues/1093
- Tested theses changes in my personal dev cluster and also the current PST cluster that's running 3 batch_procs
=> 1093 disp s1 status view improvements

conf/sds/rules/user_rules-cnm.json.tmpl
- Fix a typo in user_rules-cnm.json.tmpl making it unparseable JSON
=> Fix typo in user_rules-cnm.json.tmpl

cluster_provisioning/modules/common/mozart.tf, docker/Dockerfile
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> eccodes version update for ECMWF merger

report/opera_validator/README.md
- Updating validator readme to clarify set up instructions
=> #1121: Updating validator readme to clarify set up instructions

cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DISP_S1_STATIC.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DISP_S1.yaml, conf/schema/RunConfig_schema.L3_DISP_S1_STATIC.yaml, conf/sds/files/datasets.json, conf/sds/files/datasets.json.tmpl.asg, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/hysds-io.json.SCIFLO_L3_DISP_S1_STATIC, docker/job-spec.json.SCIFLO_L3_DISP_S1_STATIC, extractor/extract.py, opera_chimera/accountability.py, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1_STATIC.yaml, opera_chimera/precondition_functions.py, opera_chimera/wf_xml/L3_DISP_S1_STATIC.sf.xml, product2dataset/product2dataset.py, tests/unit/util/test_pge_util.py, util/pge_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- This PR integrates support for the DISP-S1-STATIC PGE which was included in the v3.0.5 release integrated in #1127 
- Currently only running as an on-demand job with fixed input data
- Add DISP-S1-STATIC SCIFLO job
- Closes #1130 
- Added & ran unit tests for DISP-S1-STATIC simulation mode
- Currently deploying test cluster
=> DISP-S1 Static Layers Workflow Integration

.gitignore, conf/AlgoParams.yaml.L3_DISP_S1.jinja2.tmpl, conf/AlgoParams.yaml.L3_DSWx_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_CSLC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_CSLC_S1_STATIC.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1.jinja2.tmpl, conf/RunConfig.yaml.L2_RTC_S1_STATIC.jinja2.tmpl, conf/RunConfig.yaml.L3_DISP_S1.jinja2.tmpl, conf/RunConfig.yaml.L3_DISP_S1_STATIC.jinja2.tmpl, conf/RunConfig.yaml.L3_DIST_S1.jinja2.tmpl, conf/RunConfig.yaml.L3_DSWx_HLS.jinja2.tmpl, conf/RunConfig.yaml.L3_DSWx_NI.jinja2.tmpl, conf/RunConfig.yaml.L3_DSWx_S1.jinja2.tmpl, conf/schema/AlgoParams_schema.L3_DISP_S1.yaml, conf/schema/AlgoParams_schema.L3_DSWx_S1.yaml, conf/settings.yaml, data_subscriber/rtc_for_dist/rtc_for_dist_query.py, opera_chimera/configs/pge_configs/PGE_L3_DISP_S1.yaml, opera_chimera/configs/pge_configs/PGE_L3_DSWx_S1.yaml, util/conf_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Issue 1125 disp s1 algo params override fix

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-releaser/main.tf, cluster_provisioning/dev-releaser/variables.tf, cluster_provisioning/dev/main.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/variables.tf
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Split asf_cnm_s_ids to many for jenkins job

cluster_provisioning/dev-e2e/main.tf, cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-releaser/main.tf, cluster_provisioning/dev-releaser/variables.tf, cluster_provisioning/dev/main.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/modules/common/main.tf, cluster_provisioning/modules/common/variables.tf
- [ADD] ...
- [CHANGE] ...
- [REMOVE] ...
=> Change dev-int to dev_int for asf_cnm_s_id

data_subscriber/asf_rtc_for_dist_download.py, data_subscriber/catalog.py, data_subscriber/rtc_for_dist/rtc_for_dist_query.py
- Bit of clean up in DIST-S1 triggering data structure. Now including `HH` and `HV` polarization data in triggering.
- https://github.com/nasa/opera-sds-pcm/issues/1153
- Tested forward processing of DIST-S1 for 10+ hours
- Tested forward and re processing of DSWx-S1 to make sure no bugs were introduced
=> 1153 dist s1 forward clean up

data_subscriber/disp_static/disp_static_query.py
mark optional field as required=False
- [CHANGE] mark optional field as required=False
#1186 
tested locally
=> issue 1186: fix(DISP-S1): CLI has optional field marked as required

tools/dataspace_s1_download.py, util/dataspace_util.py
- Customizable S1 platforms
- Geo query
- Improved Copernicus sign in options
=> Update dataspace download script

cluster_provisioning/dev-e2e/variables.tf, cluster_provisioning/dev-int/override.tf, cluster_provisioning/dev/variables.tf, cluster_provisioning/ebs-snapshot/variables.tf, cluster_provisioning/modules/common/variables.tf, conf/RunConfig.yaml.L3_DISP_NI.jinja2.tmpl, conf/pge_outputs.yaml, conf/schema/RunConfig_schema.L3_DISP_NI.yaml, conf/sds/files/datasets.json, conf/sds/rules/user_rules-cnm.json.tmpl, conf/settings.yaml, docker/hysds-io.json.SCIFLO_L3_DISP_NI, docker/hysds-io.json.pge_smoke_test, docker/job-spec.json.SCIFLO_L3_DISP_NI, docker/job-spec.json.pge_smoke_test, extractor/extract.py, opera_chimera/accountability.py, opera_chimera/configs/pge_configs/PGE_L3_DISP_NI.yaml, opera_chimera/precondition_functions.py, opera_chimera/wf_xml/L3_DISP_NI.sf.xml, pge_smoke_test/run_pge_smoke_test.sh, product2dataset/product2dataset.py, tests/unit/util/test_pge_util.py, util/pge_util.py, wrapper/opera_pge_wrapper.py, wrapper/pge_functions.py
- This PR adds support for the initial interface release of the DISP-NI PGE
- Add the DISP-NI PGE to the on-demand smoke test job
- Current DISP-NI executions use canned inputs
- Stubs for adding metadata and accountability info as needed/when available
- Compressed GSLC patterns are currently temporary pending proper naming convention from ADT
- Fixed issue with TROPO filename pattern in settings.yaml
- #1232
=> Integrate new PGE - DISP-NI 6.0.0-ER.1.0
